token: inlets
disableTransportWrapping: false
replicaCount: 1

community:
  image: inlets/inlets
  tag: 2.7.0

pro:
  enabled: false
  image: inlets/inlets-pro
  tag: 0.5.6
  remoteTcp: 192.168.100.1

serviceAccount:
  create: false
  name:

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8123

ingress:
  enabled: true
  annotations: {}
  hosts:
    - inlets.local
  tls: []
  
resources:
  requests:
    cpu: 5m
    memory: 16Mi
  limits:
    cpu: 50m
    memory: 64Mi
nodeSelector: {}
tolerations: []
affinity: {}
